services:

  mysql:
    image: mysql:8.0
    container_name: my_sql_img
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: pms
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -P 3306 --protocol=TCP -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pms-network
  pms:
    build: .
    container_name: product-service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: server
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - pms-network


volumes:
  mysql-data:


networks:
  pms-network:
    driver: bridge